amplitudes = [
    7.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
    1.0,
]

phases = [
    1.59,
    1.3,
    0.1,
    0.0,
    0.9,
    0.4,
    0.25,
    1.1,
    -0.3,
]

frequencies = [
    0.0,
    0.2,
    0.3,
    0.5,
    0.7,
    0.11,
    0.13,
    0.17,
    0.19
]